language: node_js
node_js:
- '8'
script:
- npm run travis-test && npm run compile
before_deploy:
- npm run build-storybook
deploy:
  - provider: npm
    email: julien.ducro@deskpro.com
    api_key:
      secure: "oKme+/KU4hbZQU4LX6ck+4PqDvNgaLhLR6wnsm3hP4l4MmdorFtjY6r05DjetlNW24XjNfgxIxxdKqKw1TvWTxaLy1GYoVGz+7/o1gZOuRWwe8hIL+64EYs+U91qY5CD9DCcJ9PNCnAiomc6BogrwbssAocEmTuuHwUOy0OzPGn7idrEcPynbLpK+WToLSPsN81lKy0k8+YYV8ImbS+skRCeOtVCGM9O/D3uU8QHPW5LreuxD0aZYVXGWVYKyvr3fXVcAPNSDs3NMtlWwnW/gHAPI2lnuNqC2K36vmXOykX6GeJ2+vbZaHV6VvTZpjyF70P7IjUd08MIK3QVjge0JVAg7z3x0zJKauc0PWdPHGr4eak+SDwc7fzGGgwkyw0rRZGmJ1S0nNFwngVuJAXhFhQ/b6ituLsSxEFvZm0+x4G6bOMmvIIvam34F6CGrkrRsrjnRsujJHmS49XwCJK42hA52HPp0so/zN3qUVbWj0JC1ww7y/Hapm5ufaJiZJA+y5tQqSeH2rtRNWPyHsF07i2Kw/mHft13Algh8MMnCFOEvxcuxm88e9eWviL9bndaYmtlPsaxqH6rkhT/sEpEKeI0LdWpFVf7zeEx95MDoYr749WR563EsCYvQTla0r/MuBq5bwKP5jItO39DhzSuF/yMaos7UXy1OV8Am7tnpbg="
    skip_cleanup: true
    on:
      branch: master
      tags: true
    after_success:
      - npm run storybook:deploy
  - provider: pages
    skip_cleanup: true
    github_token: $github_token
    keep-history: true
    local-dir: .site
    on:
      branch: master